version: '3.8'

services:
  backend:
    build:
      context: ../../../
      dockerfile: infra/backend/docker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - APP_HOST=0.0.0.0
      - APP_PORT=3001
    env_file:
      - ../../../application/backend/.env