# fly.toml app configuration file generated for e-punch-backend on 2025-05-13T16:57:56-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'e-punch-backend'
primary_region = 'eze'

[build]
  dockerfile = 'infra/backend/docker/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
