export const ROUTES = {
  DASHBOARD: '/dashboard',
  SCANNER: '/scanner',
  LOYALTY_PROGRAMS: '/loyalty-programs',
  LOYALTY_PROGRAMS_CREATE: '/loyalty-programs/create',
  LOYALTY_PROGRAMS_EDIT: '/loyalty-programs/:id/edit',
  BUNDLE_PROGRAMS: '/bundle-programs',
  BUNDLE_PROGRAMS_CREATE: '/bundle-programs/create',
  BUNDLE_PROGRAMS_EDIT: '/bundle-programs/:id/edit',
  DESIGN: '/design',
  WELCOME_QR: '/welcome-qr',
  ANALYTICS: '/analytics',
  ADMIN_USERS: '/admin/users',
  ADMIN_SETTINGS: '/admin/settings',
  CUSTOMERS: '/customers',
  CUSTOMER_DETAIL: '/customers/:id',
  DEMO: '/demo',
}; 